# Generated by Django 3.0.8 on 2020-07-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpage',
            options={'verbose_name_plural': 'Webpages'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name_plural': 'Websites'},
        ),
        migrations.AlterModelOptions(
            name='websitecategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
