# Generated by Django 3.0.8 on 2020-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20200712_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecategory',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
