# Generated by Django 3.0.8 on 2020-07-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20200709_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='alexa_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='meta_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
