# Generated by Django 3.0.8 on 2020-07-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websitecategory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
