# Generated by Django 3.0.8 on 2020-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_auto_20200709_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='category',
        ),
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.ManyToManyField(to='websites.WebsiteCategory'),
        ),
    ]
